[build]
builder = "nixpacks"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:8080"
PORT = "8080"

[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu"]

[phases.build]
cmds = [
  "dotnet restore Mumii.Microservices.sln",
  "dotnet publish src/ApiGateway/Mumii.ApiGateway.csproj -c Release -o /app/out"
]

[run]
cmd = "bash ./start.sh"


