[build]
builder = "dockerfile"

[docker]
dockerfilePath = "src/Services/Social/Mumii.Social.Api/Dockerfile"
context = "."

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:8083"
PORT = "8083"
SWAGGER_ENABLED = "true"


